[package]
name = "protocols_rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"
description = "HomeOS protocols"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = "0.14.5"

[build-dependencies]
capnpc = "0.14.5"