// Code generated by capnpc-go. DO NOT EDIT.

package protocols

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type RegistrationRequest struct{ capnp.Struct }

// RegistrationRequest_TypeID is the unique identifier for the type RegistrationRequest.
const RegistrationRequest_TypeID = 0x8bf557328a6bd599

func NewRegistrationRequest(s *capnp.Segment) (RegistrationRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RegistrationRequest{st}, err
}

func NewRootRegistrationRequest(s *capnp.Segment) (RegistrationRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RegistrationRequest{st}, err
}

func ReadRootRegistrationRequest(msg *capnp.Message) (RegistrationRequest, error) {
	root, err := msg.RootPtr()
	return RegistrationRequest{root.Struct()}, err
}

func (s RegistrationRequest) String() string {
	str, _ := text.Marshal(0x8bf557328a6bd599, s.Struct)
	return str
}

func (s RegistrationRequest) Name() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s RegistrationRequest) HasName() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s RegistrationRequest) NameBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s RegistrationRequest) SetName(v string) error {
	return s.Struct.SetText(0, v)
}

func (s RegistrationRequest) Callback() (string, error) {
	p, err := s.Struct.Ptr(1)
	return p.Text(), err
}

func (s RegistrationRequest) HasCallback() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s RegistrationRequest) CallbackBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return p.TextBytes(), err
}

func (s RegistrationRequest) SetCallback(v string) error {
	return s.Struct.SetText(1, v)
}

// RegistrationRequest_List is a list of RegistrationRequest.
type RegistrationRequest_List struct{ capnp.List }

// NewRegistrationRequest creates a new list of RegistrationRequest.
func NewRegistrationRequest_List(s *capnp.Segment, sz int32) (RegistrationRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return RegistrationRequest_List{l}, err
}

func (s RegistrationRequest_List) At(i int) RegistrationRequest {
	return RegistrationRequest{s.List.Struct(i)}
}

func (s RegistrationRequest_List) Set(i int, v RegistrationRequest) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s RegistrationRequest_List) String() string {
	str, _ := text.MarshalList(0x8bf557328a6bd599, s.List)
	return str
}

// RegistrationRequest_Promise is a wrapper for a RegistrationRequest promised by a client call.
type RegistrationRequest_Promise struct{ *capnp.Pipeline }

func (p RegistrationRequest_Promise) Struct() (RegistrationRequest, error) {
	s, err := p.Pipeline.Struct()
	return RegistrationRequest{s}, err
}

const schema_8f5494d9dd28283d = "x\xda\x120w`\x12d\x8dg`\x08dae\xfb" +
	"?\xf3jv\x97Q\xf8\xd7n\x06AY\xc6\xff\xb6\x1a" +
	"\x1awoN\x09\xe9g`ebg`0\x14\xedb" +
	"\x14\xd4eg`\x10\xd4,g`\xfc_P\x94_\x92" +
	"\x9f\x9c\x9f\xc3Z\xac_\x94\x9a\x9eY\\R\x94X\x92" +
	"\x99\x9f\xa7\x97\x9cX\x90W`\x15\x84$\x14\x94ZX" +
	"\x9aZ\\\xc2\xc0\x10\xc0\xc8\x18\xc8\xc1\xcc\xc2\xc0\xc0\xc2" +
	"\x082E\x8b\x81!P\x85\x991\xd0\x80\x89Q\x90\x91" +
	"Q\x84\x11$\xa8\xeb\xc5\xc0\x10\xa8\xc3\xcc\x18h\xc1\xc4" +
	"\xc8\x9f\x97\x98\x9b\xca\xc8\xc3\xc0\xc4\xc8\xc3\xc0\xf8?9" +
	"1'')19\x9b\x81\x81\x01&\x06\x08\x00\x00\xff" +
	"\xff\x97\x84,\x05"

func init() {
	schemas.Register(schema_8f5494d9dd28283d,
		0x8bf557328a6bd599)
}
