name: Build Ocaml code

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - 'ocaml/**'
      - 'protocols/**'
      - '.github/workflows/ocaml.yaml'

defaults:
  run:
    working-directory: ./ocaml

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.x
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: (macOS) Install Dependencies
        if: runner.os == 'macOS'
        run: brew install capnp

      - name: (Ubuntu) Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install capnproto

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
